version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: setup bundler
          command: gem install bundler -v 2.1.4
      - ruby/bundle-install
      - run:
          name: bundle exec rake
          command: bundle exec rake
