version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0
        environment:
          BUNDLER_VERSION: 2.3.5
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: setup bundler
          command: gem install bundler -v 2.3.5
      - ruby/bundle-install
      - run:
          name: bundle exec rake
          command: bundle exec rake
